# config.toml

username = "12345678"
password = "testpass"
interval = 600
enabled = true

[smtp]
server = "smtp.qq.com"
port = 465
sender = "test@example.com"
password = "auth"
receiver = "test@example.com"